[package]
name = "proton"
author = ["Varad Sharma"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clang-sys = "1.6.1"
env_logger = "0.10.0"
tts = "0.25.5"
